"""Edit CreateDate

Revision ID: 130fa6604ede
Revises: 95578c1af3ed
Create Date: 2024-01-24 09:51:40.113890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130fa6604ede'
down_revision = '95578c1af3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
