"""Add user relationship to Donation

Revision ID: 95578c1af3ed
Revises: 8c703f8e8d21
Create Date: 2024-01-21 23:06:59.255606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95578c1af3ed'
down_revision = '8c703f8e8d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_reservation_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservation_user_id_user', type_='foreignkey')

    # ### end Alembic commands ###
